# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Standaert Home Automation bridge add-on
version: "0.1.0"
slug: sha-bridge
description: Standaert Home Automation bridge add-on
url: "https://github.com/RockinRoel/standaert-ha-home-assistant-addons/tree/main/sha-bridge"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
uart: true
map:
  - addon_config:r
  - share:rw
options:
  mqtt: true
  debug: false
schema:
  serial_port: device(subsystem=tty)?
  mqtt: bool
  debug: bool
services:
  - mqtt:want
image: "ghcr.io/rockinroel/{arch}-sha-bridge-addon"