# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Standaert Home Automation bridge add-on
version: "0.1.0"
slug: sha_bridge
description: Standaert Home Automation bridge add-on
url: "https://github.com/RockinRoel/standaert-ha-home-assistant-addons/tree/main/sha_bridge"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  serial_port:
schema:
  serial_port: device(subsystem=tty)?
image: "ghcr.io/RockinRoel/{arch}-standaert-ha-bridge-addon"
